--------------------------- 3D HPS estimation ---------------------------
/media/pranoy/Pranoy/human3.6M/images/s_05_act_12_subact_02_ca_02/s_05_act_12_subact_02_ca_02_000971.jpg
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main_worker(args)
  File "main.py", line 330, in main_worker
    avg_train_loss  = train_epoch(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 101, in __getitem__
    print(pose_full_lath)
UnboundLocalError: local variable 'pose_full_lath' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main_worker(args)
  File "main.py", line 330, in main_worker
    avg_train_loss  = train_epoch(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 101, in __getitem__
    print(pose_full_lath)
UnboundLocalError: local variable 'pose_full_lath' referenced before assignment